### ISSUE TITLE
Unable to resolve action `cargo-generate/cargo-generate-action@v0.18`, unable to find version `v0.18`

### ISSUE THREAD

**Issue by n8henrie** [cargo-generate/cargo-generate-action#15]
Using the README as a template, I'm seeing this error:

```
Unable to resolve action `cargo-generate/cargo-generate-action@v0.18`, unable to find version `v0.18`
```

For example: https://github.com/n8henrie/rust-cli-template/actions/runs/6422633060

Spelling out the full release (`0.18.3`) seems to solve the error.

It looks like you may need to add additional tags on a release to get it to match.

I recommend either looking into tagging the `0.18.3` release as `0.18` or updating the README example to use the fully specified version.

**Comment by sassman** [comment]
with v0.18.5 it's fixed. 
Furthermore, you can now use the `@latest` version tag.
