### ISSUE TITLE
Git Error: A repo has no Head

### ISSUE THREAD

**Issue by marcoieni** [cargo-generate/cargo-generate-action#5]
I am trying to introduce this action in https://github.com/rust-github/template/pull/17 but I get an error in [CI](https://github.com/rust-github/template/runs/4050803300?check_suite_focus=true).

I think it is related to https://github.com/cargo-generate/cargo-generate/issues/406

Am I doing something wrong?

**Comment by marcoieni** [comment]
https://github.com/rust-github/template/pull/17/commits/72d996ed0d2b05d09bad7775590e018698fdba8d fixed it, because I removed the `pull_request` trigger.
Is there a plan to add support for the `pull_request` event?

**Comment by sassman** [comment]
As a workaround you might try the `ref` parameter on the `actions/checkout@v2` as you can see below, that might lead to a consistent HEAD and `cargo-generate` should not complain. (But I've not verified the proposal)

![image](https://user-images.githubusercontent.com/329682/140655614-56130b56-bf21-45be-befb-e1c78aed55a3.png)

(source: https://frontside.com/blog/2020-05-26-github-actions-pull_request/)

**Comment by marcoieni** [comment]
It doesn't work [here](https://github.com/rust-github/template/pull/24/files).

Should we use `--path` instead of `--git`? It was the solution to cargo-generate/cargo-generate#406

**Comment by sassman** [comment]
Probably that would be an idea.

**Comment by sassman** [comment]
curious if that solves now your problem

**Comment by marcoieni** [comment]
Yes, it fixed it, thanks!
See https://github.com/rust-github/template/pull/24
